#!/usr/bin/env bash
# Cavalyra iOS – generate signing.local.xcconfig from ios/.env.local
# or from environment variables (CI). Safe to run repeatedly.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/ios/.env.local"
OUT_FILE="$ROOT/ios/signing.local.xcconfig"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
fi

: "${DEVELOPMENT_TEAM:?DEVELOPMENT_TEAM is not set. Copy ios/.env.example to ios/.env.local or export it in CI.}"
: "${PROVISIONING_PROFILE_SPECIFIER:?PROVISIONING_PROFILE_SPECIFIER is not set. Copy ios/.env.example to ios/.env.local or export it in CI.}"

cat > "$OUT_FILE" <<EOF
// AUTO-GENERATED by scripts/setup-ios-signing.sh – do not edit by hand.
// Values come from ios/.env.local (local) or CI environment (Codemagic / GHA).
DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM}
PROVISIONING_PROFILE_SPECIFIER = ${PROVISIONING_PROFILE_SPECIFIER}
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = Apple Distribution
EOF

echo "✓ Wrote $OUT_FILE"
echo "  DEVELOPMENT_TEAM=${DEVELOPMENT_TEAM}"
echo "  PROVISIONING_PROFILE_SPECIFIER=${PROVISIONING_PROFILE_SPECIFIER}"
